package com.zeerqi27.etoilebridge.ui

import com.zeerqi27.etoilebridge.model.UiLanguage

data class CharacterUiText(
    val pageTitle: String,
    val heroTitle: String,
    val selectPng: String,
    val selectArcpkg: String,
    val noInputTitle: String,
    val noInputDetail: String,
    val currentInput: String,
    val inputType: String,
    val waiting: String,
    val ready: String,
    val failed: String,
    val characterInfo: String,
    val outputFileName: String,
    val publisherId: String,
    val characterId: String,
    val identifierPreview: String,
    val directory: String,
    val defaultName: String,
    val chineseName: String,
    val image: String,
    val icon: String,
    val imageInfo: String,
    val iconCrop: String,
    val positionPreview: String,
    val fileSize: String,
    val imageSize: String,
    val alpha: String,
    val alphaWarning: String,
    val iconPreview: String,
    val cropPreview: String,
    val approximateResultPreview: String,
    val characterMayExceedCanvas: String,
    val adjustIfOutsidePreview: String,
    val previewDebugInfo: String,
    val sourceSize: String,
    val drawSize: String,
    val drawOffset: String,
    val visibleBounds: String,
    val scalePivot: String,
    val intersectsCanvas: String,
    val characterOutsideCanvas: String,
    val importImageForIconCrop: String,
    val iconWithoutSourceImage: String,
    val generateIcon: String,
    val resetCrop: String,
    val cropCenterX: String,
    val cropCenterY: String,
    val cropSize: String,
    val x: String,
    val y: String,
    val scale: String,
    val reset: String,
    val center: String,
    val fitHeight: String,
    val fitWidth: String,
    val sampleDefault: String,
    val enterValue: String,
    val invalidValue: String,
    val outOfRangeClamped: String,
    val buildAndSave: String,
    val startBuild: String,
    val saveDownloads: String,
    val saveAs: String,
    val validatorPassed: String,
    val validatorFailed: String,
    val pendingFile: String,
    val finalLocation: String,
    val advancedInfo: String,
    val showDetails: String,
    val hideDetails: String,
    val indexPreview: String,
    val characterYamlPreview: String,
    val logs: String,
    val warnings: String,
    val errors: String,
    val copiedPng: String,
    val importedArcpkg: String,
    val iconGenerated: String,
    val saved: String,
    val notSaved: String,
    val none: String,
)

fun characterText(language: UiLanguage): CharacterUiText =
    if (language == UiLanguage.English) {
        CharacterUiText(
            pageTitle = "Character Editor",
            heroTitle = "Character Editor",
            selectPng = "Select character PNG",
            selectArcpkg = "Select character arcpkg",
            noInputTitle = "Select a PNG or character arcpkg",
            noInputDetail = "Create a new character package or edit an existing one.",
            currentInput = "Current input",
            inputType = "Input type",
            waiting = "Waiting",
            ready = "Ready to build",
            failed = "Failed",
            characterInfo = "Character info",
            outputFileName = "Output filename",
            publisherId = "Publisher ID",
            characterId = "Character ID",
            identifierPreview = "Identifier preview",
            directory = "Directory",
            defaultName = "Default name",
            chineseName = "Chinese name",
            image = "Character image",
            icon = "Icon",
            imageInfo = "Image info",
            iconCrop = "Icon crop",
            positionPreview = "Position preview",
            fileSize = "File size",
            imageSize = "Image size",
            alpha = "Alpha",
            alphaWarning = "This image may not have a transparent background.",
            iconPreview = "Icon preview",
            cropPreview = "Crop preview",
            approximateResultPreview = "Approximate ArcCreate result-screen preview",
            characterMayExceedCanvas = "Character may exceed the canvas",
            adjustIfOutsidePreview = "Adjust x / y / scale if it is outside the preview",
            previewDebugInfo = "Preview debug info",
            sourceSize = "Source size",
            drawSize = "Draw size",
            drawOffset = "Draw offset",
            visibleBounds = "Visible bounds",
            scalePivot = "Scale pivot",
            intersectsCanvas = "Intersects canvas",
            characterOutsideCanvas = "Character is outside the preview canvas",
            importImageForIconCrop = "Import a character PNG or character package to crop the icon.",
            iconWithoutSourceImage = "Existing icon found, but the source image is missing. Reimport the PNG to crop again.",
            generateIcon = "Generate icon",
            resetCrop = "Reset crop",
            cropCenterX = "Center X",
            cropCenterY = "Center Y",
            cropSize = "Crop size",
            x = "X",
            y = "Y",
            scale = "Scale",
            reset = "Reset",
            center = "Center",
            fitHeight = "Fit height",
            fitWidth = "Fit width",
            sampleDefault = "Sample default",
            enterValue = "Enter value",
            invalidValue = "Invalid value",
            outOfRangeClamped = "Out of range, clamped",
            buildAndSave = "Build and save",
            startBuild = "Start build",
            saveDownloads = "Save to Downloads",
            saveAs = "Save as",
            validatorPassed = "Character package validated",
            validatorFailed = "Character validation failed",
            pendingFile = "Pending file",
            finalLocation = "Final location",
            advancedInfo = "Advanced details",
            showDetails = "Show details",
            hideDetails = "Hide details",
            indexPreview = "index.yml preview",
            characterYamlPreview = "character.yml preview",
            logs = "Logs",
            warnings = "Warnings",
            errors = "Errors",
            copiedPng = "Character PNG imported",
            importedArcpkg = "Character arcpkg imported",
            iconGenerated = "Icon generated",
            saved = "Saved",
            notSaved = "Not saved",
            none = "None",
        )
    } else {
        CharacterUiText(
            pageTitle = "搭档编辑",
            heroTitle = "搭档编辑",
            selectPng = "选择搭档 PNG",
            selectArcpkg = "选择已有搭档 arcpkg",
            noInputTitle = "选择 PNG 或搭档 arcpkg",
            noInputDetail = "可以新建搭档包，也可以导入已有搭档包继续编辑。",
            currentInput = "当前输入",
            inputType = "输入类型",
            waiting = "待开始",
            ready = "可打包",
            failed = "失败",
            characterInfo = "搭档信息",
            outputFileName = "输出文件名",
            publisherId = "发布者 ID",
            characterId = "搭档识别码",
            identifierPreview = "identifier 预览",
            directory = "目录",
            defaultName = "默认名称",
            chineseName = "中文名称",
            image = "搭档原图",
            icon = "icon",
            imageInfo = "图片信息",
            iconCrop = "icon 裁剪",
            positionPreview = "位置预览",
            fileSize = "文件大小",
            imageSize = "图片尺寸",
            alpha = "透明度",
            alphaWarning = "图片可能不是透明背景。",
            iconPreview = "icon 预览",
            cropPreview = "裁剪预览",
            approximateResultPreview = "近似 ArcCreate 结果页预览",
            characterMayExceedCanvas = "角色可超出画布",
            adjustIfOutsidePreview = "若预览外不可见，请调整 x / y / scale",
            previewDebugInfo = "预览调试信息",
            sourceSize = "原图尺寸",
            drawSize = "绘制尺寸",
            drawOffset = "绘制偏移",
            visibleBounds = "可见范围",
            scalePivot = "缩放锚点",
            intersectsCanvas = "是否与画布相交",
            characterOutsideCanvas = "角色当前在预览画布外",
            importImageForIconCrop = "导入搭档 PNG 或搭档包后可裁剪 icon。",
            iconWithoutSourceImage = "已有 icon，但缺少原图，无法重新裁剪。",
            generateIcon = "生成 icon",
            resetCrop = "重置裁剪",
            cropCenterX = "中心 X",
            cropCenterY = "中心 Y",
            cropSize = "裁剪大小",
            x = "x",
            y = "y",
            scale = "scale",
            reset = "重置",
            center = "居中",
            fitHeight = "适配高度",
            fitWidth = "适配宽度",
            sampleDefault = "样例默认",
            enterValue = "输入数值",
            invalidValue = "数值无效",
            outOfRangeClamped = "超出范围，已自动限制",
            buildAndSave = "打包与保存",
            startBuild = "开始打包",
            saveDownloads = "保存到 Downloads",
            saveAs = "另存为",
            validatorPassed = "搭档包验证通过",
            validatorFailed = "搭档包验证失败",
            pendingFile = "待保存文件",
            finalLocation = "最终保存位置",
            advancedInfo = "高级信息",
            showDetails = "显示详细信息",
            hideDetails = "收起详细信息",
            indexPreview = "index.yml 预览",
            characterYamlPreview = "character.yml 预览",
            logs = "日志",
            warnings = "警告",
            errors = "错误",
            copiedPng = "搭档 PNG 已导入",
            importedArcpkg = "搭档包已导入",
            iconGenerated = "icon 已生成",
            saved = "已保存",
            notSaved = "未保存",
            none = "无",
        )
    }
