package com.zeerqi27.etoilebridge.ui

import com.zeerqi27.etoilebridge.model.UiLanguage
import com.zeerqi27.etoilebridge.model.UiPackMode
import com.zeerqi27.etoilebridge.model.UiScanStatus

data class PackUiText(
    val pageTitle: String,
    val officialMode: String,
    val arcpkgMode: String,
    val existingPackMode: String,
    val selectOfficialZip: String,
    val selectOfficialFolder: String,
    val selectArcpkgs: String,
    val selectArcpkgFolder: String,
    val selectArcpkgZip: String,
    val selectExistingPack: String,
    val selectArcpkgToAdd: String,
    val selectArcpkgFolderToAdd: String,
    val scan: String,
    val notSelected: String,
    val waiting: String,
    val scanning: String,
    val scanned: String,
    val scanFailed: String,
    val packableCount: (Int, Int) -> String,
    val officialEmptyTitle: String,
    val arcpkgEmptyTitle: String,
    val existingPackEmptyTitle: String,
    val emptyDetail: String,
    val noBundleableItems: String,
    val noBundleableItemsDetail: String,
    val packSettings: String,
    val outputFilename: String,
    val packName: String,
    val publisherId: String,
    val packId: String,
    val packIdentifierPreview: String,
    val levelIdentifierRule: String,
    val packCover: String,
    val selectCover: String,
    val replaceCover: String,
    val clearCover: String,
    val manual: String,
    val identified: String,
    val notDetectedCanChoose: String,
    val includeConvertibleOnly: String,
    val includeModeError: String,
    val noPreprocessInArcpkgMode: String,
    val levelList: String,
    val total: String,
    val enabled: String,
    val packable: String,
    val skipped: String,
    val warning: String,
    val failed: String,
    val noEnabledItems: String,
    val enabledFailedHint: String,
    val sources: String,
    val bundleAndSave: String,
    val startBundling: String,
    val saveStatus: String,
    val pendingFile: String,
    val fileSize: String,
    val finalLocation: String,
    val bundleValidationPassed: String,
    val bundleValidationFailed: String,
    val structureErrors: String,
    val pendingSave: String,
    val copyLogsAndScan: String,
    val deviceInfo: String,
    val inputInfo: String,
    val outputInfo: String,
    val logs: String,
    val validator: String,
    val none: String,
    val kept: String,
    val cleaned: String,
    val existingLevels: String,
    val addedLevels: String,
    val finalLevels: String,
    val renamedConflicts: String,
    val rebuildPack: String,
    val ignoredAddedPackEntry: String,
)

fun packText(language: UiLanguage): PackUiText =
    if (language == UiLanguage.English) {
        PackUiText(
            pageTitle = "Pack Editor",
            officialMode = "Official Pack Import",
            arcpkgMode = "Bundle arcpkg Files",
            existingPackMode = "Edit Existing Pack",
            selectOfficialZip = "Select official pack ZIP",
            selectOfficialFolder = "Select official pack folder",
            selectArcpkgs = "Select arcpkgs",
            selectArcpkgFolder = "Select arcpkg folder",
            selectArcpkgZip = "Select arcpkg ZIP",
            selectExistingPack = "Select existing pack",
            selectArcpkgToAdd = "Select arcpkg to add",
            selectArcpkgFolderToAdd = "Select arcpkg folder to add",
            scan = "Scan",
            notSelected = "Not selected",
            waiting = "Waiting",
            scanning = "Scanning",
            scanned = "Scanned",
            scanFailed = "Scan failed",
            packableCount = { ready, total -> "Bundle ready $ready / $total" },
            officialEmptyTitle = "Select an official pack ZIP or folder",
            arcpkgEmptyTitle = "Select arcpkgs, an arcpkg folder, or an arcpkg ZIP",
            existingPackEmptyTitle = "Select an existing pack arcpkg to edit",
            emptyDetail = "After scanning, level status and bundle validation will appear here.",
            noBundleableItems = "No bundleable items",
            noBundleableItemsDetail = "Check the input structure or switch modes and scan again.",
            packSettings = "Pack settings",
            outputFilename = "Output filename",
            packName = "Pack name",
            publisherId = "Publisher ID",
            packId = "Pack ID",
            packIdentifierPreview = "Pack identifier preview",
            levelIdentifierRule = "Level identifiers default to publisherId.songId. Per-level editing is available in the level list.",
            packCover = "Pack cover",
            selectCover = "Select cover",
            replaceCover = "Replace cover",
            clearCover = "Clear cover",
            manual = "Manual",
            identified = "Identified",
            notDetectedCanChoose = "Not detected; choose manually",
            includeConvertibleOnly = "Include convertible items only",
            includeModeError = "Some enabled items are not bundleable. Fix them or enable convertible-only mode.",
            noPreprocessInArcpkgMode = "arcpkg bundle mode does not need AFF preprocessing",
            levelList = "Level list",
            total = "Total",
            enabled = "Enabled",
            packable = "Bundleable",
            skipped = "Skipped",
            warning = "Warnings",
            failed = "Failed",
            noEnabledItems = "No bundleable items. Enable at least one bundleable item.",
            enabledFailedHint = "Enabled items contain failures. Fix them or enable convertible-only mode.",
            sources = "arcpkg sources",
            bundleAndSave = "Bundle and save",
            startBundling = "Start bundling",
            saveStatus = "Save status",
            pendingFile = "Pending file",
            fileSize = "File size",
            finalLocation = "Final location",
            bundleValidationPassed = "Bundle structure validated",
            bundleValidationFailed = "Bundle validation failed",
            structureErrors = "Structure errors:",
            pendingSave = "Bundle generated. Waiting for save.",
            copyLogsAndScan = "Copy logs / scan result",
            deviceInfo = "Device info",
            inputInfo = "Input info",
            outputInfo = "Output info",
            logs = "Logs",
            validator = "Validator",
            none = "None",
            kept = "Kept",
            cleaned = "Cleaned",
            existingLevels = "Existing levels",
            addedLevels = "Added levels",
            finalLevels = "Final levels",
            renamedConflicts = "Renamed conflicts",
            rebuildPack = "Rebuild pack",
            ignoredAddedPackEntry = "Ignored pack entry from added source",
        )
    } else {
        PackUiText(
            pageTitle = "曲包编辑",
            officialMode = "官方曲包导入",
            arcpkgMode = "多个 arcpkg 打包",
            existingPackMode = "编辑已有曲包",
            selectOfficialZip = "选择官方曲包 ZIP",
            selectOfficialFolder = "选择官方曲包文件夹",
            selectArcpkgs = "选择多个 arcpkg",
            selectArcpkgFolder = "选择 arcpkg 文件夹",
            selectArcpkgZip = "选择 arcpkg ZIP",
            selectExistingPack = "选择已有曲包",
            selectArcpkgToAdd = "选择追加 arcpkg",
            selectArcpkgFolderToAdd = "选择追加 arcpkg 文件夹",
            scan = "扫描",
            notSelected = "未选择",
            waiting = "待开始",
            scanning = "扫描中",
            scanned = "已扫描",
            scanFailed = "扫描失败",
            packableCount = { ready, total -> "可打包 $ready / $total" },
            officialEmptyTitle = "选择官方曲包 ZIP 或文件夹",
            arcpkgEmptyTitle = "选择多个 arcpkg、arcpkg 文件夹或 arcpkg ZIP",
            existingPackEmptyTitle = "选择已有曲包 arcpkg 开始编辑",
            emptyDetail = "扫描后会显示曲目、可打包数量和结构验证结果。",
            noBundleableItems = "没有可打包项目",
            noBundleableItemsDetail = "请检查输入结构，或切换模式后重新扫描。",
            packSettings = "曲包设置",
            outputFilename = "输出文件名",
            packName = "曲包名称",
            publisherId = "发布者 ID",
            packId = "曲包识别码",
            packIdentifierPreview = "曲包 identifier 预览",
            levelIdentifierRule = "Level identifier：每首歌默认 publisherId.songId，可在曲目列表中逐曲调整。",
            packCover = "曲包封面",
            selectCover = "选择封面",
            replaceCover = "更换封面",
            clearCover = "清除封面",
            manual = "手动指定",
            identified = "已识别",
            notDetectedCanChoose = "未识别，可手动选择",
            includeConvertibleOnly = "只打包可转换项目",
            includeModeError = "当前有不可打包项目。关闭“只打包可转换项目”时需要先修复它们。",
            noPreprocessInArcpkgMode = "多个 arcpkg 打包模式不需要 AFF 预处理",
            levelList = "曲目列表",
            total = "总数",
            enabled = "已启用",
            packable = "可打包",
            skipped = "已跳过",
            warning = "警告",
            failed = "失败",
            noEnabledItems = "没有可打包项目。请启用至少一个可打包项目。",
            enabledFailedHint = "存在已启用但不可打包的项目，请修复或开启“只打包可转换项目”。",
            sources = "arcpkg 来源",
            bundleAndSave = "打包与保存",
            startBundling = "开始打包",
            saveStatus = "保存状态",
            pendingFile = "待保存文件",
            fileSize = "文件大小",
            finalLocation = "最终位置",
            bundleValidationPassed = "曲包结构验证通过",
            bundleValidationFailed = "曲包结构验证失败",
            structureErrors = "结构异常：",
            pendingSave = "曲包已生成，等待保存。",
            copyLogsAndScan = "复制日志 / 扫描结果",
            deviceInfo = "设备信息",
            inputInfo = "输入信息",
            outputInfo = "输出信息",
            logs = "日志",
            validator = "结构验证",
            none = "无",
            kept = "保留",
            cleaned = "已清理",
            existingLevels = "已有曲目",
            addedLevels = "追加曲目",
            finalLevels = "最终曲目",
            renamedConflicts = "冲突修正",
            rebuildPack = "重新打包",
            ignoredAddedPackEntry = "已忽略追加来源中的 pack entry",
        )
    }

fun PackUiText.scanStatusLabel(status: UiScanStatus): String =
    when (status) {
        UiScanStatus.NotScanned -> waiting
        UiScanStatus.Scanning -> scanning
        UiScanStatus.Scanned -> scanned
        UiScanStatus.Failed -> scanFailed
    }

fun PackUiText.modeStartTitle(mode: UiPackMode): String =
    when (mode) {
        UiPackMode.OfficialArcaeaPack -> officialEmptyTitle
        UiPackMode.ArcpkgBundle -> arcpkgEmptyTitle
        UiPackMode.ExistingPackEdit -> existingPackEmptyTitle
    }

fun localizeKnownMessage(message: String, language: UiLanguage): String {
    if (language == UiLanguage.English) return message
    val mappings = listOf(
        "Ignored non-standard AFF file:" to "已忽略非标准 AFF 文件：",
        "Missing audio" to "缺少音频",
        "Missing chart" to "缺少谱面",
        "Missing metadata" to "缺少谱面信息",
        "Missing jacket" to "缺少曲绘",
        "Missing background" to "缺少背景",
        "Image preview failed" to "图片预览失败",
        "File does not exist" to "文件不存在",
        "No bundleable items" to "没有可打包项目",
        "Ignored pack entry from added source" to "已忽略追加来源中的 pack entry",
        "skipped" to "已跳过",
        "failed" to "失败",
        "validator passed" to "结构验证通过",
        "validator failed" to "结构验证失败",
    )
    mappings.forEach { (prefix, replacement) ->
        if (message.startsWith(prefix)) return replacement + message.removePrefix(prefix).trimStart()
    }
    return message
}
