package com.zeerqi27.etoilebridge.ui

import com.zeerqi27.etoilebridge.model.UiExtractStatus
import com.zeerqi27.etoilebridge.model.UiArcCreateAccent
import com.zeerqi27.etoilebridge.model.UiArcCreateNote
import com.zeerqi27.etoilebridge.model.UiArcCreateParticle
import com.zeerqi27.etoilebridge.model.UiArcCreateSide
import com.zeerqi27.etoilebridge.model.UiArcCreateSingleLine
import com.zeerqi27.etoilebridge.model.UiArcCreateTrack
import com.zeerqi27.etoilebridge.model.UiInputType
import com.zeerqi27.etoilebridge.model.UiLanguage
import com.zeerqi27.etoilebridge.model.UiSaveStatus
import com.zeerqi27.etoilebridge.model.UiScanStatus

data class AppText(
    val appName: String,
    val pageTitle: String,
    val settings: String,
    val page: String,
    val switchPage: String,
    val currentPage: String,
    val packConversion: String,
    val laterSupport: String,
    val cache: String,
    val versionInfo: String,
    val debugBuild: String,
    val cacheCleared: String,
    val scanComplete: String,
    val scanFailedMessage: String,
    val conversionCompletePendingSave: String,
    val saveFailedPending: String,
    val operationFailed: String,
    val extracting: String,
    val copyingInput: String,
    val scanningInput: String,
    val converting: String,
    val saving: String,
    val conversionReadyDetail: String,
    val noInputTitle: String,
    val noInputDetail: String,
    val noInputPhaseDetail: String,
    val continueAction: String,
    val projectDescription: String,
    val language: String,
    val chinese: String,
    val english: String,
    val about: String,
    val selectFolder: String,
    val selectZip: String,
    val scan: String,
    val device: String,
    val input: String,
    val inputType: String,
    val currentInput: String,
    val workspace: String,
    val projectRoot: String,
    val songRoot: String,
    val extractStatus: String,
    val scanStatus: String,
    val saveStatus: String,
    val recognition: String,
    val songId: String,
    val outputFileName: String,
    val pendingFile: String,
    val pendingFileSize: String,
    val savedMethod: String,
    val savedFileName: String,
    val savedLocation: String,
    val savedFileSize: String,
    val workspaceStatus: String,
    val detectedAff: String,
    val adoptedAff: String,
    val ignoredAff: String,
    val resources: String,
    val audio: String,
    val jacket: String,
    val background: String,
    val manualResources: String,
    val selectAudio: String,
    val selectJacket: String,
    val selectBackground: String,
    val selectSonglist: String,
    val selectPacklist: String,
    val metadata: String,
    val editMetadata: String,
    val title: String,
    val artist: String,
    val bpmText: String,
    val baseBpm: String,
    val side: String,
    val appearance: String,
    val note: String,
    val particle: String,
    val accent: String,
    val track: String,
    val singleLine: String,
    val publisherId: String,
    val levelId: String,
    val identifierPreview: String,
    val identifierOverride: String,
    val advancedInfo: String,
    val overview: String,
    val inputSummary: String,
    val lephonMappedToLight: String,
    val difficulty: String,
    val chartConstant: String,
    val ratingClass: String,
    val chartDesigner: String,
    val jacketDesigner: String,
    val affMapping: String,
    val editAffMapping: String,
    val adopt: String,
    val notAdopted: String,
    val manualMapping: String,
    val conflict: String,
    val preprocessOptions: String,
    val deleteDesignant: String,
    val fixZeroArcTap: String,
    val fixReversedArc: String,
    val expandArcResolution: String,
    val convertAndSave: String,
    val convert: String,
    val saveDownloads: String,
    val saveAs: String,
    val clearCache: String,
    val copyLogs: String,
    val copyScanResult: String,
    val warnings: String,
    val logs: String,
    val error: String,
    val errorDetails: String,
    val showErrorDetails: String,
    val hideErrorDetails: String,
    val showDetails: String,
    val hideDetails: String,
    val save: String,
    val cancel: String,
    val close: String,
    val none: String,
    val notSelected: String,
    val notPrepared: String,
    val notDetected: String,
    val notSaved: String,
    val waitingForScan: String,
    val manualTag: String,
    val identified: String,
    val automaticSource: String,
    val imageDetails: String,
    val resourceType: String,
    val fileSize: String,
    val imageDimensions: String,
    val source: String,
    val detailedPath: String,
    val showDetailedPath: String,
    val hideDetailedPath: String,
    val changeImage: String,
    val clearManualSelection: String,
    val imagePreviewFailed: String,
    val chooseManually: String,
    val manualResourceHint: String,
    val showResources: String,
    val hideResources: String,
    val enterPublisherId: String,
    val enterLevelId: String,
    val needMetadata: String,
    val missingFields: String,
    val optionalFields: String,
    val candidateSongIds: String,
    val scannedAff: String,
    val scannedResources: String,
    val backgroundNotDetected: String,
    val jacketNotDetected: String,
    val audioNotDetected: String,
    val songlistMissing: String,
    val downloadsUnavailable: String,
    val workspaceCleaned: String,
    val workspaceKept: String,
    val packDetected: String,
    val packPageLater: String,
    val convertible: String,
    val notConvertible: String,
    val pendingMetadata: String,
) {
    fun inputTypeLabel(value: UiInputType): String =
        when (value) {
            UiInputType.None -> notSelected
            UiInputType.Folder -> if (this === zhHans) "文件夹" else "Folder"
            UiInputType.Zip -> "ZIP"
        }

    fun extractStatusLabel(value: UiExtractStatus): String =
        when (value) {
            UiExtractStatus.NotExtracted -> if (this === zhHans) "未解压" else "Not extracted"
            UiExtractStatus.Extracting -> if (this === zhHans) "解压中" else "Extracting"
            UiExtractStatus.Extracted -> if (this === zhHans) "已解压" else "Extracted"
            UiExtractStatus.Failed -> if (this === zhHans) "解压失败" else "Extract failed"
        }

    fun scanStatusLabel(value: UiScanStatus): String =
        when (value) {
            UiScanStatus.NotScanned -> if (this === zhHans) "未扫描" else "Not scanned"
            UiScanStatus.Scanning -> if (this === zhHans) "扫描中" else "Scanning"
            UiScanStatus.Scanned -> if (this === zhHans) "已扫描" else "Scanned"
            UiScanStatus.Failed -> if (this === zhHans) "扫描失败" else "Scan failed"
        }

    fun saveStatusLabel(value: UiSaveStatus): String =
        when (value) {
            UiSaveStatus.NotSaved -> notSaved
            UiSaveStatus.Pending -> if (this === zhHans) "待保存" else "Pending save"
            UiSaveStatus.Saving -> if (this === zhHans) "保存中" else "Saving"
            UiSaveStatus.Saved -> if (this === zhHans) "已保存" else "Saved"
            UiSaveStatus.Failed -> if (this === zhHans) "保存失败" else "Save failed"
            UiSaveStatus.Canceled -> if (this === zhHans) "用户取消保存" else "Save canceled"
        }

    fun manual(value: String?): String? =
        value?.let { "$it ($manualTag)" }

    fun sideLabel(value: UiArcCreateSide): String =
        when (value) {
            UiArcCreateSide.Light -> if (this === zhHans) "Light（光）" else "Light"
            UiArcCreateSide.Conflict -> if (this === zhHans) "Conflict（对立）" else "Conflict"
            UiArcCreateSide.Colorless -> if (this === zhHans) "Colorless（无色）" else "Colorless"
        }

    fun noteLabel(value: UiArcCreateNote): String =
        when (value) {
            UiArcCreateNote.Inherit -> if (this === zhHans) "继承" else "Inherit"
            UiArcCreateNote.Light -> "Light"
            UiArcCreateNote.Conflict -> "Conflict"
        }

    fun particleLabel(value: UiArcCreateParticle): String =
        when (value) {
            UiArcCreateParticle.Inherit -> if (this === zhHans) "不变" else "Inherit"
            UiArcCreateParticle.Light -> if (this === zhHans) "Light（光芒侧）" else "Light"
            UiArcCreateParticle.Conflict -> if (this === zhHans) "Conflict（纷争侧）" else "Conflict"
            UiArcCreateParticle.MiraiLight -> "Mirai Light"
            UiArcCreateParticle.MiraiConflict -> "Mirai Conflict"
            UiArcCreateParticle.Colorless -> if (this === zhHans) "Colorless（消色侧）" else "Colorless"
        }

    fun accentLabel(value: UiArcCreateAccent): String =
        when (value) {
            UiArcCreateAccent.Inherit -> if (this === zhHans) "不变" else "Inherit"
            UiArcCreateAccent.Light -> if (this === zhHans) "Light（光芒侧）" else "Light"
            UiArcCreateAccent.Conflict -> if (this === zhHans) "Conflict（纷争侧）" else "Conflict"
            UiArcCreateAccent.Dynamix -> "Dynamix"
            UiArcCreateAccent.Colorless -> if (this === zhHans) "Colorless（消色侧）" else "Colorless"
        }

    fun trackLabel(value: UiArcCreateTrack): String =
        when (value) {
            UiArcCreateTrack.Inherit -> if (this === zhHans) "不变" else "Inherit"
            UiArcCreateTrack.Light -> if (this === zhHans) "Light（光芒侧）" else "Light"
            UiArcCreateTrack.Conflict -> if (this === zhHans) "Conflict（纷争侧）" else "Conflict"
            UiArcCreateTrack.Black -> "Black"
            UiArcCreateTrack.Nijuusei -> "Nijuusei"
            UiArcCreateTrack.Rei -> "Rei"
            UiArcCreateTrack.DarkVs -> "DarkVs"
            UiArcCreateTrack.Tempest -> "Tempest"
            UiArcCreateTrack.Finale -> "Finale"
            UiArcCreateTrack.Pentiment -> "Pentiment"
            UiArcCreateTrack.Arcana -> "Arcana"
            UiArcCreateTrack.Colorless -> if (this === zhHans) "Colorless（消色侧）" else "Colorless"
        }

    fun singleLineLabel(value: UiArcCreateSingleLine): String =
        when (value) {
            UiArcCreateSingleLine.None -> if (this === zhHans) "None（不启用）" else "None"
            UiArcCreateSingleLine.Light -> if (this === zhHans) "Light（光芒侧）" else "Light"
            UiArcCreateSingleLine.Conflict -> if (this === zhHans) "Conflict（纷争侧）" else "Conflict"
            UiArcCreateSingleLine.Neo -> "Neo"
        }

    companion object {
        val zhHans = AppText(
            appName = "EtoileBridge",
            pageTitle = "单曲转换",
            settings = "设置",
            page = "页面",
            switchPage = "切换页面",
            currentPage = "当前页面",
            packConversion = "曲包转换",
            laterSupport = "后续支持",
            cache = "缓存",
            versionInfo = "版本信息",
            debugBuild = "Debug build",
            cacheCleared = "缓存已清理",
            scanComplete = "扫描完成",
            scanFailedMessage = "扫描失败",
            conversionCompletePendingSave = "转换完成，等待保存",
            saveFailedPending = "保存失败，文件仍处于待保存状态",
            operationFailed = "操作失败",
            extracting = "正在解压",
            copyingInput = "正在复制输入",
            scanningInput = "正在扫描",
            converting = "正在转换",
            saving = "正在保存",
            conversionReadyDetail = "资源和谱面已就绪，可以开始转换。",
            noInputTitle = "选择 ZIP 或歌曲文件夹开始",
            noInputDetail = "导入后会自动扫描，并在这里显示可转换状态。",
            noInputPhaseDetail = "选择 ZIP 或歌曲文件夹开始。",
            continueAction = "可继续",
            projectDescription = "Arcaea 自制谱到 ArcCreate 包转换工具",
            language = "语言",
            chinese = "简体中文",
            english = "English",
            about = "关于",
            selectFolder = "选择歌曲文件夹",
            selectZip = "选择 ZIP",
            scan = "扫描",
            device = "当前设备",
            input = "输入",
            inputType = "输入类型",
            currentInput = "当前输入",
            workspace = "工作目录",
            projectRoot = "项目根目录",
            songRoot = "歌曲目录",
            extractStatus = "解压状态",
            scanStatus = "扫描状态",
            saveStatus = "保存状态",
            recognition = "识别结果",
            songId = "songId",
            outputFileName = "输出文件名",
            pendingFile = "待保存文件",
            pendingFileSize = "待保存文件大小",
            savedMethod = "保存方式",
            savedFileName = "文件名",
            savedLocation = "最终保存位置",
            savedFileSize = "已保存文件大小",
            workspaceStatus = "workspace 状态",
            detectedAff = "检测到的 AFF",
            adoptedAff = "采用的 AFF",
            ignoredAff = "忽略的 AFF",
            resources = "资源",
            audio = "音频",
            jacket = "曲绘",
            background = "背景",
            manualResources = "手动资源",
            selectAudio = "选择音频",
            selectJacket = "选择曲绘",
            selectBackground = "选择背景",
            selectSonglist = "选择 songlist",
            selectPacklist = "选择 packlist",
            metadata = "谱面信息",
            editMetadata = "编辑信息",
            title = "曲名",
            artist = "曲师",
            bpmText = "BPM 显示文本",
            baseBpm = "baseBpm",
            side = "side",
            appearance = "ArcCreate 外观",
            note = "Note",
            particle = "粒子特效",
            accent = "判定线和连击数",
            track = "轨道",
            singleLine = "Single Line",
            publisherId = "发布者 ID",
            levelId = "谱面识别码",
            identifierPreview = "identifier 预览",
            identifierOverride = "完整 identifier",
            advancedInfo = "高级信息",
            overview = "概览",
            inputSummary = "选择 ZIP 或歌曲文件夹后会自动扫描",
            lephonMappedToLight = "Lephon → Light",
            difficulty = "难度",
            chartConstant = "谱面定数",
            ratingClass = "ratingClass",
            chartDesigner = "谱师",
            jacketDesigner = "曲绘设计",
            affMapping = "AFF 映射",
            editAffMapping = "编辑 AFF 映射",
            adopt = "采用",
            notAdopted = "不采用",
            manualMapping = "手动映射",
            conflict = "冲突",
            preprocessOptions = "预处理选项",
            deleteDesignant = "删除 designant 行",
            fixZeroArcTap = "修复 0ms arc+arctap",
            fixReversedArc = "修复 arc 起止时间反向",
            expandArcResolution = "展开 timinggroup arcresolution",
            convertAndSave = "转换与保存",
            convert = "开始转换",
            saveDownloads = "保存到 Downloads",
            saveAs = "另存为",
            clearCache = "清理缓存",
            copyLogs = "复制日志",
            copyScanResult = "复制扫描结果",
            warnings = "警告",
            logs = "日志",
            error = "错误",
            errorDetails = "错误详情",
            showErrorDetails = "显示错误详情",
            hideErrorDetails = "隐藏错误详情",
            showDetails = "显示详细信息",
            hideDetails = "收起详细信息",
            save = "保存",
            cancel = "取消",
            close = "关闭",
            none = "无",
            notSelected = "未选择",
            notPrepared = "未复制",
            notDetected = "未识别",
            notSaved = "未保存",
            waitingForScan = "等待扫描",
            manualTag = "手动指定",
            identified = "已识别",
            automaticSource = "自动识别",
            imageDetails = "图片详情",
            resourceType = "类型",
            fileSize = "文件大小",
            imageDimensions = "图片尺寸",
            source = "来源",
            detailedPath = "详细路径",
            showDetailedPath = "显示详细路径",
            hideDetailedPath = "隐藏详细路径",
            changeImage = "更换图片",
            clearManualSelection = "清除手动指定",
            imagePreviewFailed = "图片预览失败，但不影响转换",
            chooseManually = "可手动选择",
            manualResourceHint = "更多手动资源",
            showResources = "展开资源",
            hideResources = "收起资源",
            enterPublisherId = "请输入发布者 ID",
            enterLevelId = "请输入谱面识别码",
            needMetadata = "待填写信息",
            missingFields = "缺失字段",
            optionalFields = "可选字段",
            candidateSongIds = "候选 songId",
            scannedAff = "扫描到的 AFF",
            scannedResources = "扫描到的资源文件",
            backgroundNotDetected = "背景未识别，可继续转换或手动选择",
            jacketNotDetected = "曲绘未识别，可手动选择，也可留空继续",
            audioNotDetected = "缺少音频，请手动选择音频",
            songlistMissing = "缺少 songlist，可手动选择或手动填写信息",
            downloadsUnavailable = "保存到 Downloads 仅支持 Android 10 及以上，当前系统请使用另存为保存文件",
            workspaceCleaned = "已清理",
            workspaceKept = "未清理",
            packDetected = "检测到曲包结构",
            packPageLater = "当前页面只支持单曲转换，曲包转换将在后续独立页面支持。",
            convertible = "可转换",
            notConvertible = "不可转换",
            pendingMetadata = "待填写信息",
        )

        val englishText = AppText(
            appName = "EtoileBridge",
            pageTitle = "Single Song",
            settings = "Settings",
            page = "Page",
            switchPage = "Switch page",
            currentPage = "Current page",
            packConversion = "Pack conversion",
            laterSupport = "Coming later",
            cache = "Cache",
            versionInfo = "Version",
            debugBuild = "Debug build",
            cacheCleared = "Cache cleared",
            scanComplete = "Scan complete",
            scanFailedMessage = "Scan failed",
            conversionCompletePendingSave = "Conversion complete. Waiting for save.",
            saveFailedPending = "Save failed. The file is still pending.",
            operationFailed = "Operation failed",
            extracting = "Extracting",
            copyingInput = "Copying input",
            scanningInput = "Scanning",
            converting = "Converting",
            saving = "Saving",
            conversionReadyDetail = "Resources and charts are ready. You can start conversion.",
            noInputTitle = "Select a ZIP or song folder to begin",
            noInputDetail = "The input will be scanned automatically after import, and the conversion status will appear here.",
            noInputPhaseDetail = "Select a ZIP or song folder to begin.",
            continueAction = "Continue",
            projectDescription = "Convert Arcaea fanmade charts into ArcCreate packages",
            language = "Language",
            chinese = "简体中文",
            english = "English",
            about = "About",
            selectFolder = "Select song folder",
            selectZip = "Select ZIP",
            scan = "Scan",
            device = "Device",
            input = "Input",
            inputType = "Input type",
            currentInput = "Current input",
            workspace = "Workspace",
            projectRoot = "Project root",
            songRoot = "Song root",
            extractStatus = "Extract status",
            scanStatus = "Scan status",
            saveStatus = "Save status",
            recognition = "Recognition",
            songId = "songId",
            outputFileName = "Output file name",
            pendingFile = "Pending file",
            pendingFileSize = "Pending file size",
            savedMethod = "Save method",
            savedFileName = "File name",
            savedLocation = "Saved location",
            savedFileSize = "Saved file size",
            workspaceStatus = "Workspace status",
            detectedAff = "Detected AFF",
            adoptedAff = "Adopted AFF",
            ignoredAff = "Ignored AFF",
            resources = "Resources",
            audio = "Audio",
            jacket = "Jacket",
            background = "Background",
            manualResources = "Manual resources",
            selectAudio = "Select audio",
            selectJacket = "Select jacket",
            selectBackground = "Select background",
            selectSonglist = "Select songlist",
            selectPacklist = "Select packlist",
            metadata = "Metadata",
            editMetadata = "Edit metadata",
            title = "Title",
            artist = "Artist",
            bpmText = "BPM text",
            baseBpm = "baseBpm",
            side = "side",
            appearance = "ArcCreate appearance",
            note = "Note",
            particle = "Particle",
            accent = "Accent",
            track = "Track",
            singleLine = "Single Line",
            publisherId = "Publisher ID",
            levelId = "Level ID",
            identifierPreview = "Identifier preview",
            identifierOverride = "Full identifier",
            advancedInfo = "Advanced info",
            overview = "Overview",
            inputSummary = "Choose a ZIP or song folder to scan automatically",
            lephonMappedToLight = "Lephon -> Light",
            difficulty = "Difficulty",
            chartConstant = "Chart constant",
            ratingClass = "ratingClass",
            chartDesigner = "Chart designer",
            jacketDesigner = "Jacket designer",
            affMapping = "AFF mapping",
            editAffMapping = "Edit AFF mapping",
            adopt = "Adopt",
            notAdopted = "Not adopted",
            manualMapping = "Manual mapping",
            conflict = "Conflict",
            preprocessOptions = "Preprocess options",
            deleteDesignant = "Delete designant lines",
            fixZeroArcTap = "Fix 0ms arc+arctap",
            fixReversedArc = "Fix reversed arc time",
            expandArcResolution = "Expand timinggroup arcresolution",
            convertAndSave = "Convert and Save",
            convert = "Start conversion",
            saveDownloads = "Save to Downloads",
            saveAs = "Save as",
            clearCache = "Clear cache",
            copyLogs = "Copy logs",
            copyScanResult = "Copy scan result",
            warnings = "Warnings",
            logs = "Logs",
            error = "Error",
            errorDetails = "Error details",
            showErrorDetails = "Show error details",
            hideErrorDetails = "Hide error details",
            showDetails = "Show details",
            hideDetails = "Hide details",
            save = "Save",
            cancel = "Cancel",
            close = "Close",
            none = "None",
            notSelected = "Not selected",
            notPrepared = "Not prepared",
            notDetected = "Not detected",
            notSaved = "Not saved",
            waitingForScan = "Waiting for scan",
            manualTag = "manual",
            identified = "Identified",
            automaticSource = "Auto detected",
            imageDetails = "Image details",
            resourceType = "Type",
            fileSize = "File size",
            imageDimensions = "Image dimensions",
            source = "Source",
            detailedPath = "Detailed path",
            showDetailedPath = "Show path",
            hideDetailedPath = "Hide path",
            changeImage = "Change image",
            clearManualSelection = "Clear manual selection",
            imagePreviewFailed = "Image preview failed; conversion is not affected",
            chooseManually = "Choose manually",
            manualResourceHint = "More manual resources",
            showResources = "Show resources",
            hideResources = "Hide resources",
            enterPublisherId = "Enter publisher ID",
            enterLevelId = "Enter level ID",
            needMetadata = "Need metadata",
            missingFields = "Missing fields",
            optionalFields = "Optional fields",
            candidateSongIds = "Candidate songIds",
            scannedAff = "Scanned AFF",
            scannedResources = "Scanned resources",
            backgroundNotDetected = "Background not detected; conversion can continue",
            jacketNotDetected = "Jacket not detected; choose one manually or leave it empty",
            audioNotDetected = "Missing audio; select an audio file",
            songlistMissing = "Missing songlist; choose one or fill metadata manually",
            downloadsUnavailable = "Save to Downloads requires Android 10 or newer. Use Save As on this device.",
            workspaceCleaned = "Cleaned",
            workspaceKept = "Kept",
            packDetected = "Pack structure detected",
            packPageLater = "This page only supports single-song conversion. Pack conversion will be added on a separate page later.",
            convertible = "Convertible",
            notConvertible = "Not convertible",
            pendingMetadata = "Need metadata",
        )
    }
}

fun textFor(language: UiLanguage): AppText =
    when (language) {
        UiLanguage.ZhHans -> AppText.zhHans
        UiLanguage.English -> AppText.englishText
    }
